# Copyright (c) 2025-2026 ByteDance Ltd. and/or its affiliates
# SPDX-License-Identifier: Apache-2.0

r"""Radial pair-correlation estimator for electrons on a torus."""

from collections.abc import Mapping
from typing import Any

import jax
from jax import numpy as jnp

from jaqmc.array_types import PRNGKey
from jaqmc.data import BatchedData, Data
from jaqmc.estimator.base import Estimator
from jaqmc.utils.config import configurable_dataclass
from jaqmc.utils.torus import get_torus_lattice
from jaqmc.utils.wiring import runtime_dep

__all__ = ["TorusPairCorrelation"]


def _gauss_reduce(tau: complex) -> tuple[complex, complex]:
    """Return a Gauss-reduced basis for the lattice generated by ``1, tau``.

    Returns:
        Two complex lattice vectors, with the first being a shortest nonzero
        vector of the lattice.
    """
    first = 1.0 + 0.0j
    second = tau
    while True:
        if abs(second) < abs(first):
            first, second = second, first
        projection = round(
            (first.real * second.real + first.imag * second.imag) / abs(first) ** 2
        )
        if projection == 0:
            return first, second
        second -= projection * first


@configurable_dataclass
class TorusPairCorrelation(Estimator):
    r"""Radial pair correlation :math:`g(r)` on a general torus.

    Electron coordinates are fractional pairs :math:`(u,v)`, with physical
    positions

    .. math::

        z=L_1(u+\tau v), \qquad
        L_1^2\operatorname{Im}\tau=2\pi N_\phi\ell_B^2.

    Pair distances use the minimum-image convention and are reported in
    magnetic-length units. The histogram extends to half the shortest nonzero
    lattice-vector length. Inside this radius every radial shell is a complete
    annulus, so division by its exact area gives an unbiased radial
    normalization for arbitrary torus shape.

    The accumulated correlation is normalized over walkers and devices on
    every evaluation step. :meth:`finalize_state` averages it over steps and
    returns both ``pair_correlation`` and the bin centers
    ``pair_correlation:r``.

    Args:
        bins: Number of radial histogram bins.
        flux: Positive number of magnetic flux quanta :math:`N_\phi`.
        tau: Torus modular parameter in the upper half-plane.
        data_field: Name of the field holding fractional torus coordinates.
        name: Prefix used for evaluation-digest keys.
    """

    bins: int = 200
    flux: int = 1
    tau: complex = runtime_dep(default=1j)
    data_field: str = runtime_dep(default="electrons")
    name: str = "pair_correlation"

    def __post_init__(self) -> None:
        if (
            not isinstance(self.bins, int)
            or isinstance(self.bins, bool)
            or self.bins <= 0
        ):
            raise ValueError(f"bins must be a positive integer. Got {self.bins!r}.")
        if (
            not isinstance(self.flux, int)
            or isinstance(self.flux, bool)
            or self.flux <= 0
        ):
            raise ValueError(f"flux must be a positive integer. Got {self.flux!r}.")

        tau = complex(self.tau)
        if not jnp.isfinite(tau.real) or not jnp.isfinite(tau.imag):
            raise ValueError(f"tau must be finite. Got {tau!r}.")
        if tau.imag <= 0:
            raise ValueError(
                "tau must lie in the upper half-plane, so its imaginary "
                f"part must be positive. Got {tau!r}."
            )
        self.tau = tau

    def init(self, data: Data, rngs: PRNGKey) -> dict[str, jnp.ndarray]:
        del data, rngs
        l1, l2, area = get_torus_lattice(self.flux, self.tau)
        zero = jnp.zeros_like(l1)
        self._lattice = jnp.stack(
            [jnp.stack([l1, zero]), jnp.stack([l2.real, l2.imag])]
        )

        reduced_first, reduced_second = _gauss_reduce(self.tau)
        self._reduced_lattice = l1 * jnp.asarray(
            [
                [reduced_first.real, reduced_first.imag],
                [reduced_second.real, reduced_second.imag],
            ]
        )
        self._inv_reduced_lattice = jnp.linalg.inv(self._reduced_lattice)
        grid = jnp.meshgrid(jnp.arange(-1, 2), jnp.arange(-1, 2), indexing="ij")
        shift_indices = jnp.stack(grid, axis=-1).reshape(-1, 2)
        self._neighbor_shifts = shift_indices @ self._reduced_lattice

        self._max_distance = jnp.linalg.norm(self._reduced_lattice[0]) / 2
        self._bin_edges = jnp.linspace(0.0, self._max_distance, self.bins + 1)
        self._shell_areas = jnp.pi * (
            self._bin_edges[1:] ** 2 - self._bin_edges[:-1] ** 2
        )
        self._area = area

        shape = (jax.device_count(), self.bins)
        return {
            "histogram": jnp.zeros(shape),
            "compensation": jnp.zeros(shape),
        }

    def _pair_distances(self, electrons: jnp.ndarray) -> jnp.ndarray:
        """Compute upper-triangle minimum-image pair distances.

        Returns:
            Flattened distances for every walker and unordered electron pair.
        """
        cartesian = electrons @ self._lattice
        displacement = cartesian[..., :, None, :] - cartesian[..., None, :, :]

        # Center in a reduced fundamental parallelogram, then inspect its nine
        # neighboring images to select the Wigner-Seitz representative.
        fractional = displacement @ self._inv_reduced_lattice
        centered = (fractional + 0.5) % 1.0 - 0.5
        centered_displacement = centered @ self._reduced_lattice
        candidates = centered_displacement[..., None, :] + self._neighbor_shifts
        distances = jnp.min(jnp.linalg.norm(candidates, axis=-1), axis=-1)

        nelec = electrons.shape[-2]
        return distances[:, *jnp.triu_indices(nelec, 1)].reshape(-1)

    def evaluate_batch_walkers(
        self,
        params: Any,
        batched_data: BatchedData,
        prev_walker_stats: Mapping[str, Any],
        state: dict[str, jnp.ndarray],
        rngs: PRNGKey,
    ) -> tuple[dict[str, Any], dict[str, jnp.ndarray]]:
        del params, prev_walker_stats, rngs
        electrons = batched_data.data[self.data_field]
        if electrons.ndim != 3 or electrons.shape[-1] != 2:
            raise ValueError(
                "Batched torus electron coordinates must have shape "
                "(batch, n_electrons, 2), with the last axis ordered as "
                f"(u, v). Got {electrons.shape}."
            )

        batch_size, nelec, _ = electrons.shape
        pair_distances = self._pair_distances(electrons)
        counts = jnp.histogram(pair_distances, self.bins, (0.0, self._max_distance))[0]

        # Factor 2 converts i < j to i != j. The global batch size makes the
        # independently accumulated device histograms sum to one step's g(r).
        global_batch_size = batch_size * jax.device_count()
        increment = (
            counts * 2 * self._area / (global_batch_size * nelec**2 * self._shell_areas)
        )
        adjusted = increment - state["compensation"]
        new_sum = state["histogram"] + adjusted
        new_compensation = (new_sum - state["histogram"]) - adjusted
        return {}, {"histogram": new_sum, "compensation": new_compensation}

    def reduce(self, walker_stats: Mapping[str, Any]) -> dict[str, Any]:
        del walker_stats
        return {}

    def finalize_stats(
        self, mean_stats: Mapping[str, Any], state: dict[str, jnp.ndarray]
    ) -> dict[str, Any]:
        del mean_stats, state
        return {}

    def finalize_state(
        self, state: dict[str, jnp.ndarray], *, n_steps: int
    ) -> dict[str, Any]:
        correlation = jnp.sum(state["histogram"], axis=0) / n_steps
        bin_centers = (self._bin_edges[:-1] + self._bin_edges[1:]) / 2
        return {
            self.name: correlation,
            f"{self.name}:r": bin_centers,
            f"{self.name}:n_steps": n_steps,
        }
